openapi: 3.0.0
info:
  title: "Azure Data Exfiltration Lab OpenAPI"
  version: 0.0.1
paths:
  /:
    get:
      summary: "Do something"
      parameters:
        - in: query
          name: host
          schema:
            type: string
      responses:
        "200":
          description: "Successful operation"
